% Global variables for MatRANS
global omega nu ny y c g nrhs nu_T streaming turb susp beta_s U_1m U_2m ...
    icb Hind_set t0 mu_d Rough C_lim beta_star sigma_do alphaW betaW ...
    sigmaW sigma_star coef1 coef2 beta_0 rho g s Shields_cU Shields_cD ...
    nyc w_s w_s0 cb yc Px T h_m ny v nhs iwave r phi ikbc iextrap ...
    ioutplot iturbsup sigma_p iconv depth S ib n filt_U filt_K filt_W ...
    filt_C d noutput k_N kbc ...
    R_beta R_k R_omega alpha0 alpha_star0 beta_star0 ... 
    t_ud U_ud Ut_ud ... % User-defined velocity / acceleration variables
    w_f d_50 b hiding_coef ref_conc_coef ... % Added for sediment mixtures
    Umvec tnvec Omegavec
